### ISSUE TITLE
Useless Algorithm

### ISSUE THREAD

**Issue by misyltoad** [ikizir/HohhaDynamicXOR#18]
It's impossible to be unbreakable as you claim. Therefore meaning the algorithm does not solve the problem it was made to solve rendering it useless.

**Comment by ikizir** [comment]
You're right Joshua.
It's a mistake to claim scientifically that an encryption algorithm is unbreakable.
But, as I elaborated in detail at front page, any meaningful attack complexity of this algorithm is higher than the number of atoms in universe.
