### ISSUE TITLE
The Wiki tab on Github is very powerful

### ISSUE THREAD

**Issue by thagabe** [ikizir/HohhaDynamicXOR#7]
Use it to reduce the size of the README.md as it should just come with simple instructions or descriptions.

**Comment by ikizir** [comment]
Thank you Gabe. Can you show me how?
I have really very nice "visual proofs" for randomness
Can you organize the wiki for me? 
I will put visual proofs, benchmarks etc.
I am changing the algorithm, writing/fixing the code, writing the paper for the conferance and updating wiki&readme. And my English is terrible :)
You are way better than me in documentation
It will be very helpful if you take the responsability of documentation & readme.
For example, I need to add something similar to this page:
https://vikingvpn.com/blogs/security/visualizing-weak-encryption-experiments-with-aes
With those visual proofs, people will easily see that the algorithm works.
Thank you for your kind help again :)
Believe me you will see it's worth doing that!

**Comment by ikizir** [comment]
If you give me your e-mail address, I can send you the benchmarks, visuals etc. and you can write&organize as you wish.

**Comment by Logic-gate** [comment]
If you are new to github, [Github's documentation](https://help.github.com/articles/about-github-wikis/) is straight forward.  
However, if you are looking for collaborators to help you draft the wiki...laconically relaying the project's goal, scheme, methods...and so on...you'll have to wait for someone who is interested enough and is adequately knowledgeable.

**Comment by stylemistake** [comment]
@ikizir I've created a few pages in Wiki, check it out:

https://github.com/ikizir/HohhaDynamicXOR/wiki

And remove this information from the README file, and put a reference to Wiki instead, because it should contain minimum information required to compile and execute your code. (Usually no more than 200 lines of text.)

Ok?

**Comment by ikizir** [comment]
Thank you @stylemistake 
Edit README too.
You know better how to do it. I will merge
