### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [ikizir/HohhaDynamicXOR#8]
Would you like to add more error handling for return values from functions like the following?
- [malloc](http://pubs.opengroup.org/onlinepubs/9699919799/functions/malloc.html) ⇒ [Base64Encode](https://github.com/ikizir/HohhaDynamicXOR/blob/ad962a0c35523b5b797aa15368d2d869e72e146a/HohhaDynamicXOR.c#L239)
- [lseek](http://pubs.opengroup.org/onlinepubs/9699919799/functions/lseek.html) ⇒ [EncryptFile](https://github.com/ikizir/HohhaDynamicXOR/blob/ad962a0c35523b5b797aa15368d2d869e72e146a/HohhaDynamicXOR.c#L1384)

**Comment by ikizir** [comment]
Thank you elfring. I will add error checking.

**Comment by elfring** [comment]
I do not like [the use of the assert macro](https://github.com/ikizir/HohhaDynamicXOR/commit/87900c599cfa3d630919e24d7933e915cb2a7e20#diff-ae21c9ddb43e7bf58ec564c2a88b8a7cR1185) because unexpected results will still be ignored if the preprocessor symbol "`NDEBUG`" will be defined. I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html) a bit more.

**Comment by ikizir** [comment]
You're right elfring.
I personally don't like to use them either.
I am focusing on developing to optimizing the algorithm and write "quick code" sometimes.
Just let's remember this. I will fix all.
Thank you

**Comment by elfring** [comment]
How do you think about to move the implementations for your algorithms to separate source files?
Should other functions call them only from a corresponding software library eventually?
